
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teach?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

devtools:
  livereload:
    enabled: true
    port: 35729
  restart:
    enabled: true

pagehelper:
  auto-dialect: true
  reasonable: true
  support-methods-arguments: true

mybatis:
  mapper-locations: classpath*:mappers/*.xml
